### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by eNV25** [eNV25/mpdlrc#10]
- [x] config: Add support for `$MPD_HOST` and `$MPD_PORT`
  This can be done in `config.Default`.
- [x] widgetlyrics: remove use of `views.CellView`
  `WidgetLyrics` should use views.View directly. This shouldn't be too hard, most of `updateModel` can be reused.
- [x] app: add status bar
  This status bar should display song information like the `Name` and `Artist`. It could also display errors.
- [ ] app: better error messages
  The interfaces in `interfaces.go` need to update to return error if needed.
  A status bar could be added to display non-fatal errors.
- [x] app: use `context.Context` or similar for Update methods.
- [x] #14
